apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: platform-sample-api
  namespace: platform-demo
spec:
  securityPolicy:
    name: platform-prod-armor
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 8080
