apiVersion: v1
kind: Namespace
metadata:
  name: platform-demo
  labels:
    owner: platform-team
    environment: base
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
