input {
  http {
    host => "0.0.0.0"
    port => 5001
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "service" => "jenkins"
      "event.dataset" => "jenkins.pipeline"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "jenkins-pipeline-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
