apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: platform-demo

labels:
  - pairs:
      environment: prod

replicas:
  - name: platform-sample-api
    count: 3

images:
  - name: us-central1-docker.pkg.dev/example-project/platform/platform-sample-api
    newName: us-central1-docker.pkg.dev/PROJECT_ID/platform/platform-sample-api
    newTag: bootstrap
