apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-platform-repo.git
    targetRevision: main
    path: GCP/cloud-engineer-skill-projects/08-gitops-with-argo-cd-on-gke/apps/sample-api/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

