pipeline {
  agent any

  stages {
    stage('Install') {
      steps {
        sh 'python3 -m venv .venv'
        sh '. .venv/bin/activate && pip install -r requirements.txt'
      }
    }
    stage('Quality') {
      steps {
        sh '. .venv/bin/activate && ruff check .'
        sh '. .venv/bin/activate && PYTHONPATH=src pytest -q'
      }
    }
    stage('Build Image') {
      steps {
        sh 'docker build -t incident-copilot:${BUILD_NUMBER} .'
      }
    }
    stage('Deploy Helm') {
      when { branch 'main' }
      steps {
        sh 'helm upgrade --install incident-copilot ./helm/incident-copilot --namespace mlops --create-namespace'
      }
    }
  }
}
