apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-serving
  namespace: mlops-demo
  annotations:
    iam.gke.io/gcp-service-account: ml-serving@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drift-monitor
  namespace: mlops-demo
  annotations:
    iam.gke.io/gcp-service-account: ml-monitor@PROJECT_ID.iam.gserviceaccount.com
