apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quiz
resources:
  - ../../base
images:
  - name: quiz-api
    newName: quiz-api
    newTag: local
  - name: quiz-web
    newName: quiz-web
    newTag: local
