apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-gpu
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-gpu
  template:
    metadata:
      labels:
        app: ollama-gpu
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: ollama
          image: ollama/ollama:0.5.1
          ports:
            - containerPort: 11434
          resources:
            limits:
              nvidia.com/gpu: 1
