name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t automlops-api ./backend

    - name: Run Container Test
      run: |
        docker run -d -p 8000:8000 automlops-api
        sleep 5
        curl http://localhost:8000
name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t automlops-api ./backend

    - name: Run Container Test
      run: |
        docker run -d -p 8000:8000 automlops-api
        sleep 5
        curl http://localhost:8000