apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: platform-demo

labels:
  - pairs:
      environment: dev

replicas:
  - name: platform-sample-api
    count: 1

images:
  - name: us-central1-docker.pkg.dev/example-project/platform/platform-sample-api
    newTag: dev
