apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: mlops-demo
labels:
  - pairs:
      environment: prod
images:
  - name: us-central1-docker.pkg.dev/PROJECT_ID/mlops/model-serving
    newTag: bootstrap
  - name: us-central1-docker.pkg.dev/PROJECT_ID/mlops/training
    newTag: bootstrap
  - name: us-central1-docker.pkg.dev/PROJECT_ID/mlops/mlflow
    newTag: bootstrap
