apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iarsingh/upSkilling.git
    targetRevision: main
    path: GCP/mlops_interview_portfolio/01-gke-ml-platform-blueprint/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
