apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: jenkins-pipeline-*
    jsonData:
      index: jenkins-pipeline-*
      timeField: "@timestamp"
      esVersion: "8.0.0"
    editable: true
