grafana:
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  persistence:
    enabled: true
    size: 10Gi

prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 4Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
