---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart webapp
  ansible.builtin.service:
    name: webapp
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

